Add $BASEDIR variable to bundle script

diff --git a/bundle b/bundle
--- a/bundle
+++ b/bundle
@@ -1,3 +1,6 @@
 #!/usr/bin/env zsh
 
-brew bundle dump --force --describe --file=./homebrew/brewfile --no-lock
+BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+
+echo "<<< STARTING BREW BUNDLE >>>\n"
+brew bundle dump --force --describe --file=./homebrew/brewfile --no-lock && echo "Homebrew dumped a bundle in $BASEDIR/homebrew/brewfile.\n" || echo "Homebrew failed to dump a bundle.\n"
